### ISSUE TITLE
Validator not working

### ISSUE THREAD

**Issue by tiefpunkt** [SpaceApi-archive/OpenSpaceLint#84]
When validating feeds by copy&pasting the json into the validator, the validation fails with the AdBlock error message in both chromium and firefox on linux. I use AdBlock in both, but either disabling AdBlock completely nor whitelisting the domain fixes the issue. Thus, I cannot validate the feed without publishing it first.

**Comment by tiefpunkt** [comment]
Seems to be related to the feed I'm analyzing, as it also happens after publishing the json and using that one in the validator. The space in question is RaumZeitLabor. With other spaces, it seems to work fine.

**Comment by tiefpunkt** [comment]
Found it. The "°" in the unit for the temperature sensor breaks the validator. If I take it out, it works.

**Comment by slopjong** [comment]
Thanks for the hint. This issue is related to #50.

The problem is the escape function in javascript which is not totally compatible with php's urldecode. Until now I haven't found a workaround. I've just googled [PHP rawUrlDecode() == JavaScript decodeURIComponent()](http://stackoverflow.com/a/5952090) which I'm going to test next days.
