### ISSUE TITLE
Temperature sensor units

### ISSUE THREAD

**Issue by tiefpunkt** [SpaceApi-archive/OpenSpaceLint#85]
Temperature units with special characters like "°" are not all that useful, since they don't provide any benefits. A simple "C" for celsius should be enough.

**Comment by slopjong** [comment]
Think of the client business logic. Every app consuming the spaceapi endpoints then needs to add ° to most temperature units but not to all. This means it must explicitly check what unit is actually used. If the units are already correctly provided the apps can directly render the units and this is the benefit of it.

**Comment by tiefpunkt** [comment]
From a security standpoint, apps should not directly display the value of any string field in the first place.

**Comment by slopjong** [comment]
Doesn't this hardly depend on the language? Not every language does interpret javascript just like that. With 'directly' I meant after filtering injected code but with no extra checks to correct the units.

Update: it also depends on how the endpoints are consumed. I don't see what bad should happen if a Qt application is writing the values to labels with no database involved. Injected binary data should be displayed as weird characters. The more web/database technologies are used the more security issues must be considered.

**Comment by tiefpunkt** [comment]
I guess filtering injected code is a bigger hassle than simple replacing the units, but I see your point. I guess it's a design thing, so it's your choice in the end ;)

**Comment by slopjong** [comment]
Injected code must always be filtered, no matter what unit is used. These are two different things we were mixing up.

The issue you were describing was sucking me since a year already and I didn't find out what the cause exactly was. With your ticket I had a closer look at it and finally I understook the reason and solved it in commit 97888cf. :-)

It had to do with the implementations of how javascript and php urlencode and decode, in combination with an apache configuration which I didn't know before.

I'm glad you reported this issue.

**Comment by slopjong** [comment]
I closed the ticket because the actual issue was solved but I need to get an overview of what's still open. But you can continue to comment on this topic, I'll read it sooner than later as time allows me.
